# Generated by Django 3.2.12 on 2022-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
