# Generated by Django 3.2.12 on 2022-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0002_auto_20220219_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votable',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='votables.Comment'),
        ),
        migrations.AlterField(
            model_name='votable',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, to='votables.Upvote'),
        ),
    ]
