# Generated by Django 3.2.12 on 2022-02-21 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votables', '0003_auto_20220219_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='isActive',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='amount',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='votable',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='votable',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='votable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votables.votable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upvote',
            name='sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upvote',
            name='upvote_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upvote',
            name='votable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='votables.votable'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votables.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
