# Generated by Django 3.2.12 on 2022-02-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0004_auto_20220221_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='votable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votables', to='votables.votable'),
        ),
    ]
