# Generated by Django 3.2.12 on 2022-02-25 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votables', '0005_alter_upvote_votable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='votable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='votables.votable'),
        ),
        migrations.AlterField(
            model_name='votable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votables', to=settings.AUTH_USER_MODEL),
        ),
    ]
