# Generated by Django 3.2.12 on 2022-03-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0006_auto_20220225_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='votable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votables.votable'),
        ),
    ]
