# Generated by Django 3.2.12 on 2022-03-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0007_alter_upvote_votable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='terminated',
        ),
        migrations.AlterField(
            model_name='comment',
            name='votable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='votables.votable'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='votables.comment'),
        ),
    ]
