# Generated by Django 3.2.12 on 2022-03-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0008_auto_20220315_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='votable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
