# Generated by Django 3.2.12 on 2022-03-15 14:00

from django.db import migrations, models
import votables.models


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0009_votable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=votables.models.getImagePath),
        ),
    ]
