# Generated by Django 3.2.12 on 2022-03-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0011_auto_20220315_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='votables.votable'),
        ),
    ]
