# Generated by Django 3.2.12 on 2022-03-15 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votables', '0012_alter_comment_votable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('votable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='votables.votable')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received', to=settings.AUTH_USER_MODEL)),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent', to=settings.AUTH_USER_MODEL)),
                ('votable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='votables.votable')),
            ],
        ),
    ]
