# Generated by Django 3.2.12 on 2022-03-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0013_share_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votable',
            options={'ordering': ['-created']},
        ),
    ]
