# Generated by Django 3.2.12 on 2022-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0018_auto_20220325_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='votable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='votable_images'),
        ),
    ]
