# Generated by Django 3.2.12 on 2022-03-26 18:16

from django.db import migrations, models
import votables.models


class Migration(migrations.Migration):

    dependencies = [
        ('votables', '0019_auto_20220326_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=votables.models.upload_to),
        ),
    ]
